sudo: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:git-core/ppa'
    packages:
      - git

language: go

go:
  - 1.8.x
  - 1.9.x
  - master

branches:
  only:
    - master

matrix:
  allow_failures:
    - go: master

script:  make
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - go-getter_osx
    - go-getter.exe
    - go-getter
  skip_cleanup: true